alter table if exists author drop constraint if exists FKdrat19m9ril5oorj2kxu0xodq;
alter table if exists book drop constraint if exists FKl13kra4clx2eu99u9p1xpj2gv;
alter table if exists book drop constraint if exists FKevj08i66fju1rmrbddcvu3nxy;
alter table if exists book drop constraint if exists FKam9riv8y6rjwkua1gapdfew4j;
alter table if exists book drop constraint if exists FKpmv0yeqvng13trnm9so4aaq04;
alter table if exists book_author drop constraint if exists FKbjqhp85wjv8vpr0beygh6jsgo;
alter table if exists book_author drop constraint if exists FKddiaong6i51tm6bl4ordev531;
alter table if exists book_copy drop constraint if exists FKoavt6bvftkhay4lwegb3xr2wj;
alter table if exists book_copy drop constraint if exists FK97ooaf6exwl2n7hfx40gt3mjk;
alter table if exists bookshelf drop constraint if exists FKb7b2wqfkshgjlnfq80wuuv2rq;
alter table if exists catalog drop constraint if exists FKth4yhq6olxgommh0qflkf5fqx;
drop table if exists author cascade;
drop table if exists book cascade;
drop table if exists book_author cascade;
drop table if exists book_basket cascade;
drop table if exists book_copy cascade;
drop table if exists bookshelf cascade;
drop table if exists catalog cascade;
drop table if exists category cascade;
drop table if exists editor cascade;
drop table if exists library cascade;
drop table if exists member cascade;
alter table if exists author drop constraint if exists FKdrat19m9ril5oorj2kxu0xodq;
alter table if exists book drop constraint if exists FKl13kra4clx2eu99u9p1xpj2gv;
alter table if exists book drop constraint if exists FKevj08i66fju1rmrbddcvu3nxy;
alter table if exists book drop constraint if exists FKam9riv8y6rjwkua1gapdfew4j;
alter table if exists book drop constraint if exists FKpmv0yeqvng13trnm9so4aaq04;
alter table if exists book_author drop constraint if exists FKbjqhp85wjv8vpr0beygh6jsgo;
alter table if exists book_author drop constraint if exists FKddiaong6i51tm6bl4ordev531;
alter table if exists book_copy drop constraint if exists FKoavt6bvftkhay4lwegb3xr2wj;
alter table if exists book_copy drop constraint if exists FK97ooaf6exwl2n7hfx40gt3mjk;
alter table if exists bookshelf drop constraint if exists FKb7b2wqfkshgjlnfq80wuuv2rq;
alter table if exists catalog drop constraint if exists FKth4yhq6olxgommh0qflkf5fqx;
drop table if exists author cascade;
drop table if exists book cascade;
drop table if exists book_author cascade;
drop table if exists book_basket cascade;
drop table if exists book_copy cascade;
drop table if exists bookshelf cascade;
drop table if exists catalog cascade;
drop table if exists category cascade;
drop table if exists editor cascade;
drop table if exists library cascade;
drop table if exists member cascade;
alter table if exists author drop constraint if exists FKdrat19m9ril5oorj2kxu0xodq;
alter table if exists book drop constraint if exists FKl13kra4clx2eu99u9p1xpj2gv;
alter table if exists book drop constraint if exists FKevj08i66fju1rmrbddcvu3nxy;
alter table if exists book drop constraint if exists FKam9riv8y6rjwkua1gapdfew4j;
alter table if exists book drop constraint if exists FKpmv0yeqvng13trnm9so4aaq04;
alter table if exists book_author drop constraint if exists FKbjqhp85wjv8vpr0beygh6jsgo;
alter table if exists book_author drop constraint if exists FKddiaong6i51tm6bl4ordev531;
alter table if exists book_copy drop constraint if exists FKoavt6bvftkhay4lwegb3xr2wj;
alter table if exists book_copy drop constraint if exists FK97ooaf6exwl2n7hfx40gt3mjk;
alter table if exists bookshelf drop constraint if exists FKb7b2wqfkshgjlnfq80wuuv2rq;
alter table if exists catalog drop constraint if exists FKth4yhq6olxgommh0qflkf5fqx;
drop table if exists author cascade;
drop table if exists book cascade;
drop table if exists book_author cascade;
drop table if exists book_basket cascade;
drop table if exists book_copy cascade;
drop table if exists bookshelf cascade;
drop table if exists catalog cascade;
drop table if exists category cascade;
drop table if exists editor cascade;
drop table if exists library cascade;
drop table if exists member cascade;
alter table if exists author drop constraint if exists FKdrat19m9ril5oorj2kxu0xodq;
alter table if exists book drop constraint if exists FKl13kra4clx2eu99u9p1xpj2gv;
alter table if exists book drop constraint if exists FKevj08i66fju1rmrbddcvu3nxy;
alter table if exists book drop constraint if exists FKam9riv8y6rjwkua1gapdfew4j;
alter table if exists book drop constraint if exists FKpmv0yeqvng13trnm9so4aaq04;
alter table if exists book_author drop constraint if exists FKbjqhp85wjv8vpr0beygh6jsgo;
alter table if exists book_author drop constraint if exists FKddiaong6i51tm6bl4ordev531;
alter table if exists book_copy drop constraint if exists FKoavt6bvftkhay4lwegb3xr2wj;
alter table if exists book_copy drop constraint if exists FK97ooaf6exwl2n7hfx40gt3mjk;
alter table if exists bookshelf drop constraint if exists FKb7b2wqfkshgjlnfq80wuuv2rq;
alter table if exists catalog drop constraint if exists FKth4yhq6olxgommh0qflkf5fqx;
drop table if exists author cascade;
drop table if exists book cascade;
drop table if exists book_author cascade;
drop table if exists book_basket cascade;
drop table if exists book_copy cascade;
drop table if exists bookshelf cascade;
drop table if exists catalog cascade;
drop table if exists category cascade;
drop table if exists editor cascade;
drop table if exists library cascade;
drop table if exists member cascade;
alter table if exists Author drop constraint if exists FK9cfjr4iigbmvf2svg1xtlpe1w;
alter table if exists Book drop constraint if exists FK60uxj6f35trm5vyu02bxrveiq;
alter table if exists Book drop constraint if exists FKl0npaol2i7v4pfv6uhbe950g4;
alter table if exists Book drop constraint if exists FK48vokckvl9udy5g3dyve2nkuq;
alter table if exists Book drop constraint if exists FKdht85pyx6r4v2968du7fs0ul9;
alter table if exists book_author drop constraint if exists FKi58evljxutyg4crade5qq9chg;
alter table if exists book_author drop constraint if exists FKdtgq5x5jxnpkbl7iuo1hsmcc6;
alter table if exists book_copy drop constraint if exists FKoavt6bvftkhay4lwegb3xr2wj;
alter table if exists book_copy drop constraint if exists FKkcm8cbxp7owpvqab9qgeaname;
alter table if exists bookshelf drop constraint if exists FKb7b2wqfkshgjlnfq80wuuv2rq;
alter table if exists catalog drop constraint if exists FKth4yhq6olxgommh0qflkf5fqx;
drop table if exists Author cascade;
drop table if exists Book cascade;
drop table if exists book_author cascade;
drop table if exists book_basket cascade;
drop table if exists book_copy cascade;
drop table if exists bookshelf cascade;
drop table if exists catalog cascade;
drop table if exists category cascade;
drop table if exists editor cascade;
drop table if exists library cascade;
drop table if exists Member cascade;
alter table if exists author drop constraint if exists FKdrat19m9ril5oorj2kxu0xodq;
alter table if exists book drop constraint if exists FKl13kra4clx2eu99u9p1xpj2gv;
alter table if exists book drop constraint if exists FKevj08i66fju1rmrbddcvu3nxy;
alter table if exists book drop constraint if exists FKam9riv8y6rjwkua1gapdfew4j;
alter table if exists book drop constraint if exists FKpmv0yeqvng13trnm9so4aaq04;
alter table if exists book_author drop constraint if exists FKbjqhp85wjv8vpr0beygh6jsgo;
alter table if exists book_author drop constraint if exists FKddiaong6i51tm6bl4ordev531;
alter table if exists book_copy drop constraint if exists FKoavt6bvftkhay4lwegb3xr2wj;
alter table if exists book_copy drop constraint if exists FK97ooaf6exwl2n7hfx40gt3mjk;
alter table if exists bookshelf drop constraint if exists FKb7b2wqfkshgjlnfq80wuuv2rq;
alter table if exists catalog drop constraint if exists FKth4yhq6olxgommh0qflkf5fqx;
drop table if exists author cascade;
drop table if exists book cascade;
drop table if exists book_author cascade;
drop table if exists book_basket cascade;
drop table if exists book_copy cascade;
drop table if exists bookshelf cascade;
drop table if exists catalog cascade;
drop table if exists category cascade;
drop table if exists editor cascade;
drop table if exists library cascade;
drop table if exists member cascade;
alter table if exists book drop constraint if exists FKevj08i66fju1rmrbddcvu3nxy;
alter table if exists book drop constraint if exists FKam9riv8y6rjwkua1gapdfew4j;
alter table if exists book drop constraint if exists FKpmv0yeqvng13trnm9so4aaq04;
alter table if exists book_author drop constraint if exists FKbjqhp85wjv8vpr0beygh6jsgo;
alter table if exists book_author drop constraint if exists FKddiaong6i51tm6bl4ordev531;
alter table if exists book_copy drop constraint if exists FKoavt6bvftkhay4lwegb3xr2wj;
alter table if exists book_copy drop constraint if exists FK97ooaf6exwl2n7hfx40gt3mjk;
alter table if exists bookshelf drop constraint if exists FKb7b2wqfkshgjlnfq80wuuv2rq;
alter table if exists catalog drop constraint if exists FKth4yhq6olxgommh0qflkf5fqx;
drop table if exists author cascade;
drop table if exists book cascade;
drop table if exists book_author cascade;
drop table if exists book_basket cascade;
drop table if exists book_copy cascade;
drop table if exists bookshelf cascade;
drop table if exists catalog cascade;
drop table if exists category cascade;
drop table if exists editor cascade;
drop table if exists library cascade;
drop table if exists member cascade;
alter table if exists book drop constraint if exists FKevj08i66fju1rmrbddcvu3nxy;
alter table if exists book drop constraint if exists FKam9riv8y6rjwkua1gapdfew4j;
alter table if exists book drop constraint if exists FKpmv0yeqvng13trnm9so4aaq04;
alter table if exists book_author drop constraint if exists FKbjqhp85wjv8vpr0beygh6jsgo;
alter table if exists book_author drop constraint if exists FKddiaong6i51tm6bl4ordev531;
alter table if exists book_copy drop constraint if exists FKoavt6bvftkhay4lwegb3xr2wj;
alter table if exists book_copy drop constraint if exists FK97ooaf6exwl2n7hfx40gt3mjk;
alter table if exists bookshelf drop constraint if exists FKb7b2wqfkshgjlnfq80wuuv2rq;
alter table if exists catalog drop constraint if exists FKth4yhq6olxgommh0qflkf5fqx;
drop table if exists author cascade;
drop table if exists book cascade;
drop table if exists book_author cascade;
drop table if exists book_basket cascade;
drop table if exists book_copy cascade;
drop table if exists bookshelf cascade;
drop table if exists catalog cascade;
drop table if exists category cascade;
drop table if exists editor cascade;
drop table if exists library cascade;
drop table if exists member cascade;
alter table if exists book drop constraint if exists FKevj08i66fju1rmrbddcvu3nxy;
alter table if exists book drop constraint if exists FKam9riv8y6rjwkua1gapdfew4j;
alter table if exists book drop constraint if exists FKpmv0yeqvng13trnm9so4aaq04;
alter table if exists book_author drop constraint if exists FKbjqhp85wjv8vpr0beygh6jsgo;
alter table if exists book_author drop constraint if exists FKddiaong6i51tm6bl4ordev531;
alter table if exists book_copy drop constraint if exists FKoavt6bvftkhay4lwegb3xr2wj;
alter table if exists book_copy drop constraint if exists FK97ooaf6exwl2n7hfx40gt3mjk;
alter table if exists bookshelf drop constraint if exists FKb7b2wqfkshgjlnfq80wuuv2rq;
alter table if exists catalog drop constraint if exists FKth4yhq6olxgommh0qflkf5fqx;
drop table if exists author cascade;
drop table if exists book cascade;
drop table if exists book_author cascade;
drop table if exists book_basket cascade;
drop table if exists book_copy cascade;
drop table if exists bookshelf cascade;
drop table if exists catalog cascade;
drop table if exists category cascade;
drop table if exists editor cascade;
drop table if exists library cascade;
drop table if exists member cascade;
alter table if exists book drop constraint if exists FKevj08i66fju1rmrbddcvu3nxy;
alter table if exists book drop constraint if exists FKam9riv8y6rjwkua1gapdfew4j;
alter table if exists book drop constraint if exists FKpmv0yeqvng13trnm9so4aaq04;
alter table if exists book_author drop constraint if exists FKbjqhp85wjv8vpr0beygh6jsgo;
alter table if exists book_author drop constraint if exists FKddiaong6i51tm6bl4ordev531;
alter table if exists book_copy drop constraint if exists FKoavt6bvftkhay4lwegb3xr2wj;
alter table if exists book_copy drop constraint if exists FK97ooaf6exwl2n7hfx40gt3mjk;
alter table if exists bookshelf drop constraint if exists FKb7b2wqfkshgjlnfq80wuuv2rq;
alter table if exists catalog drop constraint if exists FKth4yhq6olxgommh0qflkf5fqx;
drop table if exists author cascade;
drop table if exists book cascade;
drop table if exists book_author cascade;
drop table if exists book_basket cascade;
drop table if exists book_copy cascade;
drop table if exists bookshelf cascade;
drop table if exists catalog cascade;
drop table if exists category cascade;
drop table if exists editor cascade;
drop table if exists library cascade;
drop table if exists member cascade;
alter table if exists book drop constraint if exists FKevj08i66fju1rmrbddcvu3nxy;
alter table if exists book drop constraint if exists FKam9riv8y6rjwkua1gapdfew4j;
alter table if exists book drop constraint if exists FKpmv0yeqvng13trnm9so4aaq04;
alter table if exists book_author drop constraint if exists FKbjqhp85wjv8vpr0beygh6jsgo;
alter table if exists book_author drop constraint if exists FKddiaong6i51tm6bl4ordev531;
alter table if exists book_copy drop constraint if exists FKoavt6bvftkhay4lwegb3xr2wj;
alter table if exists book_copy drop constraint if exists FK97ooaf6exwl2n7hfx40gt3mjk;
alter table if exists bookshelf drop constraint if exists FKb7b2wqfkshgjlnfq80wuuv2rq;
alter table if exists catalog drop constraint if exists FKth4yhq6olxgommh0qflkf5fqx;
drop table if exists author cascade;
drop table if exists book cascade;
drop table if exists book_author cascade;
drop table if exists book_basket cascade;
drop table if exists book_copy cascade;
drop table if exists bookshelf cascade;
drop table if exists catalog cascade;
drop table if exists category cascade;
drop table if exists editor cascade;
drop table if exists library cascade;
drop table if exists member cascade;
alter table if exists book drop constraint if exists FKevj08i66fju1rmrbddcvu3nxy;
alter table if exists book drop constraint if exists FKam9riv8y6rjwkua1gapdfew4j;
alter table if exists book drop constraint if exists FKpmv0yeqvng13trnm9so4aaq04;
alter table if exists book_author drop constraint if exists FKbjqhp85wjv8vpr0beygh6jsgo;
alter table if exists book_author drop constraint if exists FKddiaong6i51tm6bl4ordev531;
alter table if exists book_copy drop constraint if exists FKoavt6bvftkhay4lwegb3xr2wj;
alter table if exists book_copy drop constraint if exists FK97ooaf6exwl2n7hfx40gt3mjk;
alter table if exists bookshelf drop constraint if exists FKb7b2wqfkshgjlnfq80wuuv2rq;
alter table if exists catalog drop constraint if exists FKth4yhq6olxgommh0qflkf5fqx;
drop table if exists author cascade;
drop table if exists book cascade;
drop table if exists book_author cascade;
drop table if exists book_basket cascade;
drop table if exists book_copy cascade;
drop table if exists bookshelf cascade;
drop table if exists catalog cascade;
drop table if exists category cascade;
drop table if exists editor cascade;
drop table if exists library cascade;
drop table if exists member cascade;
alter table if exists book drop constraint if exists FKevj08i66fju1rmrbddcvu3nxy;
alter table if exists book drop constraint if exists FKam9riv8y6rjwkua1gapdfew4j;
alter table if exists book drop constraint if exists FKpmv0yeqvng13trnm9so4aaq04;
alter table if exists book_author drop constraint if exists FKbjqhp85wjv8vpr0beygh6jsgo;
alter table if exists book_author drop constraint if exists FKddiaong6i51tm6bl4ordev531;
alter table if exists book_copy drop constraint if exists FKoavt6bvftkhay4lwegb3xr2wj;
alter table if exists book_copy drop constraint if exists FK97ooaf6exwl2n7hfx40gt3mjk;
alter table if exists bookshelf drop constraint if exists FKb7b2wqfkshgjlnfq80wuuv2rq;
alter table if exists catalog drop constraint if exists FKth4yhq6olxgommh0qflkf5fqx;
drop table if exists author cascade;
drop table if exists book cascade;
drop table if exists book_author cascade;
drop table if exists book_basket cascade;
drop table if exists book_copy cascade;
drop table if exists bookshelf cascade;
drop table if exists catalog cascade;
drop table if exists category cascade;
drop table if exists editor cascade;
drop table if exists library cascade;
drop table if exists member cascade;
alter table if exists book drop constraint if exists FKevj08i66fju1rmrbddcvu3nxy;
alter table if exists book drop constraint if exists FKam9riv8y6rjwkua1gapdfew4j;
alter table if exists book drop constraint if exists FKpmv0yeqvng13trnm9so4aaq04;
alter table if exists book_author drop constraint if exists FKbjqhp85wjv8vpr0beygh6jsgo;
alter table if exists book_author drop constraint if exists FKddiaong6i51tm6bl4ordev531;
alter table if exists book_copy drop constraint if exists FKoavt6bvftkhay4lwegb3xr2wj;
alter table if exists book_copy drop constraint if exists FK97ooaf6exwl2n7hfx40gt3mjk;
alter table if exists bookshelf drop constraint if exists FKb7b2wqfkshgjlnfq80wuuv2rq;
alter table if exists catalog drop constraint if exists FKth4yhq6olxgommh0qflkf5fqx;
drop table if exists author cascade;
drop table if exists book cascade;
drop table if exists book_author cascade;
drop table if exists book_basket cascade;
drop table if exists book_copy cascade;
drop table if exists bookshelf cascade;
drop table if exists catalog cascade;
drop table if exists category cascade;
drop table if exists editor cascade;
drop table if exists library cascade;
drop table if exists member cascade;
alter table if exists book drop constraint if exists FKevj08i66fju1rmrbddcvu3nxy;
alter table if exists book drop constraint if exists FKam9riv8y6rjwkua1gapdfew4j;
alter table if exists book drop constraint if exists FKpmv0yeqvng13trnm9so4aaq04;
alter table if exists book_author drop constraint if exists FKbjqhp85wjv8vpr0beygh6jsgo;
alter table if exists book_author drop constraint if exists FKddiaong6i51tm6bl4ordev531;
alter table if exists book_copy drop constraint if exists FKoavt6bvftkhay4lwegb3xr2wj;
alter table if exists book_copy drop constraint if exists FK97ooaf6exwl2n7hfx40gt3mjk;
alter table if exists bookshelf drop constraint if exists FKb7b2wqfkshgjlnfq80wuuv2rq;
alter table if exists catalog drop constraint if exists FKth4yhq6olxgommh0qflkf5fqx;
drop table if exists author cascade;
drop table if exists book cascade;
drop table if exists book_author cascade;
drop table if exists book_basket cascade;
drop table if exists book_copy cascade;
drop table if exists bookshelf cascade;
drop table if exists catalog cascade;
drop table if exists category cascade;
drop table if exists editor cascade;
drop table if exists library cascade;
drop table if exists member cascade;
alter table if exists book drop constraint if exists FKevj08i66fju1rmrbddcvu3nxy;
alter table if exists book drop constraint if exists FKam9riv8y6rjwkua1gapdfew4j;
alter table if exists book drop constraint if exists FKpmv0yeqvng13trnm9so4aaq04;
alter table if exists book_author drop constraint if exists FKbjqhp85wjv8vpr0beygh6jsgo;
alter table if exists book_author drop constraint if exists FKddiaong6i51tm6bl4ordev531;
alter table if exists book_copy drop constraint if exists FKoavt6bvftkhay4lwegb3xr2wj;
alter table if exists book_copy drop constraint if exists FK97ooaf6exwl2n7hfx40gt3mjk;
alter table if exists bookshelf drop constraint if exists FKb7b2wqfkshgjlnfq80wuuv2rq;
alter table if exists catalog drop constraint if exists FKth4yhq6olxgommh0qflkf5fqx;
drop table if exists author cascade;
drop table if exists book cascade;
drop table if exists book_author cascade;
drop table if exists book_basket cascade;
drop table if exists book_copy cascade;
drop table if exists bookshelf cascade;
drop table if exists catalog cascade;
drop table if exists category cascade;
drop table if exists editor cascade;
drop table if exists library cascade;
drop table if exists member cascade;
alter table if exists book drop constraint if exists FKevj08i66fju1rmrbddcvu3nxy;
alter table if exists book drop constraint if exists FKam9riv8y6rjwkua1gapdfew4j;
alter table if exists book drop constraint if exists FKpmv0yeqvng13trnm9so4aaq04;
alter table if exists book_author drop constraint if exists FKbjqhp85wjv8vpr0beygh6jsgo;
alter table if exists book_author drop constraint if exists FKddiaong6i51tm6bl4ordev531;
alter table if exists book_copy drop constraint if exists FKoavt6bvftkhay4lwegb3xr2wj;
alter table if exists book_copy drop constraint if exists FK97ooaf6exwl2n7hfx40gt3mjk;
alter table if exists bookshelf drop constraint if exists FKb7b2wqfkshgjlnfq80wuuv2rq;
alter table if exists catalog drop constraint if exists FKth4yhq6olxgommh0qflkf5fqx;
drop table if exists author cascade;
drop table if exists book cascade;
drop table if exists book_author cascade;
drop table if exists book_basket cascade;
drop table if exists book_copy cascade;
drop table if exists bookshelf cascade;
drop table if exists catalog cascade;
drop table if exists category cascade;
drop table if exists editor cascade;
drop table if exists library cascade;
drop table if exists member cascade;
alter table if exists book drop constraint if exists FKevj08i66fju1rmrbddcvu3nxy;
alter table if exists book drop constraint if exists FKam9riv8y6rjwkua1gapdfew4j;
alter table if exists book drop constraint if exists FKpmv0yeqvng13trnm9so4aaq04;
alter table if exists book_author drop constraint if exists FKbjqhp85wjv8vpr0beygh6jsgo;
alter table if exists book_author drop constraint if exists FKddiaong6i51tm6bl4ordev531;
alter table if exists book_copy drop constraint if exists FKoavt6bvftkhay4lwegb3xr2wj;
alter table if exists book_copy drop constraint if exists FK97ooaf6exwl2n7hfx40gt3mjk;
alter table if exists bookshelf drop constraint if exists FKb7b2wqfkshgjlnfq80wuuv2rq;
alter table if exists catalog drop constraint if exists FKth4yhq6olxgommh0qflkf5fqx;
drop table if exists author cascade;
drop table if exists book cascade;
drop table if exists book_author cascade;
drop table if exists book_basket cascade;
drop table if exists book_copy cascade;
drop table if exists bookshelf cascade;
drop table if exists catalog cascade;
drop table if exists category cascade;
drop table if exists editor cascade;
drop table if exists library cascade;
drop table if exists member cascade;
alter table if exists book drop constraint if exists FKevj08i66fju1rmrbddcvu3nxy;
alter table if exists book drop constraint if exists FKam9riv8y6rjwkua1gapdfew4j;
alter table if exists book drop constraint if exists FKpmv0yeqvng13trnm9so4aaq04;
alter table if exists book_author drop constraint if exists FKbjqhp85wjv8vpr0beygh6jsgo;
alter table if exists book_author drop constraint if exists FKddiaong6i51tm6bl4ordev531;
alter table if exists book_copy drop constraint if exists FKoavt6bvftkhay4lwegb3xr2wj;
alter table if exists book_copy drop constraint if exists FK97ooaf6exwl2n7hfx40gt3mjk;
alter table if exists bookshelf drop constraint if exists FKb7b2wqfkshgjlnfq80wuuv2rq;
alter table if exists catalog drop constraint if exists FKth4yhq6olxgommh0qflkf5fqx;
drop table if exists author cascade;
drop table if exists book cascade;
drop table if exists book_author cascade;
drop table if exists book_basket cascade;
drop table if exists book_copy cascade;
drop table if exists bookshelf cascade;
drop table if exists catalog cascade;
drop table if exists category cascade;
drop table if exists editor cascade;
drop table if exists library cascade;
drop table if exists member cascade;
alter table if exists book drop constraint if exists FKevj08i66fju1rmrbddcvu3nxy;
alter table if exists book drop constraint if exists FKam9riv8y6rjwkua1gapdfew4j;
alter table if exists book drop constraint if exists FKpmv0yeqvng13trnm9so4aaq04;
alter table if exists book_author drop constraint if exists FKbjqhp85wjv8vpr0beygh6jsgo;
alter table if exists book_author drop constraint if exists FKddiaong6i51tm6bl4ordev531;
alter table if exists book_copy drop constraint if exists FKoavt6bvftkhay4lwegb3xr2wj;
alter table if exists book_copy drop constraint if exists FK97ooaf6exwl2n7hfx40gt3mjk;
alter table if exists bookshelf drop constraint if exists FKb7b2wqfkshgjlnfq80wuuv2rq;
alter table if exists catalog drop constraint if exists FKth4yhq6olxgommh0qflkf5fqx;
drop table if exists author cascade;
drop table if exists book cascade;
drop table if exists book_author cascade;
drop table if exists book_basket cascade;
drop table if exists book_copy cascade;
drop table if exists bookshelf cascade;
drop table if exists catalog cascade;
drop table if exists category cascade;
drop table if exists editor cascade;
drop table if exists library cascade;
drop table if exists member cascade;
alter table if exists book drop constraint if exists FKevj08i66fju1rmrbddcvu3nxy;
alter table if exists book drop constraint if exists FKam9riv8y6rjwkua1gapdfew4j;
alter table if exists book drop constraint if exists FKpmv0yeqvng13trnm9so4aaq04;
alter table if exists book_author drop constraint if exists FKbjqhp85wjv8vpr0beygh6jsgo;
alter table if exists book_author drop constraint if exists FKddiaong6i51tm6bl4ordev531;
alter table if exists book_copy drop constraint if exists FKoavt6bvftkhay4lwegb3xr2wj;
alter table if exists book_copy drop constraint if exists FK97ooaf6exwl2n7hfx40gt3mjk;
alter table if exists bookshelf drop constraint if exists FKb7b2wqfkshgjlnfq80wuuv2rq;
alter table if exists catalog drop constraint if exists FKth4yhq6olxgommh0qflkf5fqx;
drop table if exists author cascade;
drop table if exists book cascade;
drop table if exists book_author cascade;
drop table if exists book_basket cascade;
drop table if exists book_copy cascade;
drop table if exists bookshelf cascade;
drop table if exists catalog cascade;
drop table if exists category cascade;
drop table if exists editor cascade;
drop table if exists library cascade;
drop table if exists member cascade;
alter table if exists book drop constraint if exists FKevj08i66fju1rmrbddcvu3nxy;
alter table if exists book drop constraint if exists FKam9riv8y6rjwkua1gapdfew4j;
alter table if exists book drop constraint if exists FKpmv0yeqvng13trnm9so4aaq04;
alter table if exists book_author drop constraint if exists FKbjqhp85wjv8vpr0beygh6jsgo;
alter table if exists book_author drop constraint if exists FKddiaong6i51tm6bl4ordev531;
alter table if exists book_copy drop constraint if exists FKoavt6bvftkhay4lwegb3xr2wj;
alter table if exists book_copy drop constraint if exists FK97ooaf6exwl2n7hfx40gt3mjk;
alter table if exists bookshelf drop constraint if exists FKb7b2wqfkshgjlnfq80wuuv2rq;
alter table if exists catalog drop constraint if exists FKth4yhq6olxgommh0qflkf5fqx;
drop table if exists author cascade;
drop table if exists book cascade;
drop table if exists book_author cascade;
drop table if exists book_basket cascade;
drop table if exists book_copy cascade;
drop table if exists bookshelf cascade;
drop table if exists catalog cascade;
drop table if exists category cascade;
drop table if exists editor cascade;
drop table if exists library cascade;
drop table if exists member cascade;
alter table if exists book drop constraint if exists FKevj08i66fju1rmrbddcvu3nxy;
alter table if exists book drop constraint if exists FKam9riv8y6rjwkua1gapdfew4j;
alter table if exists book drop constraint if exists FKpmv0yeqvng13trnm9so4aaq04;
alter table if exists book_author drop constraint if exists FKbjqhp85wjv8vpr0beygh6jsgo;
alter table if exists book_author drop constraint if exists FKddiaong6i51tm6bl4ordev531;
alter table if exists book_copy drop constraint if exists FKoavt6bvftkhay4lwegb3xr2wj;
alter table if exists book_copy drop constraint if exists FK97ooaf6exwl2n7hfx40gt3mjk;
alter table if exists bookshelf drop constraint if exists FKb7b2wqfkshgjlnfq80wuuv2rq;
alter table if exists catalog drop constraint if exists FKth4yhq6olxgommh0qflkf5fqx;
drop table if exists author cascade;
drop table if exists book cascade;
drop table if exists book_author cascade;
drop table if exists book_basket cascade;
drop table if exists book_copy cascade;
drop table if exists bookshelf cascade;
drop table if exists catalog cascade;
drop table if exists category cascade;
drop table if exists editor cascade;
drop table if exists library cascade;
drop table if exists member cascade;
alter table if exists book drop constraint if exists FKevj08i66fju1rmrbddcvu3nxy;
alter table if exists book drop constraint if exists FKam9riv8y6rjwkua1gapdfew4j;
alter table if exists book drop constraint if exists FKpmv0yeqvng13trnm9so4aaq04;
alter table if exists book_author drop constraint if exists FKbjqhp85wjv8vpr0beygh6jsgo;
alter table if exists book_author drop constraint if exists FKddiaong6i51tm6bl4ordev531;
alter table if exists book_copy drop constraint if exists FKoavt6bvftkhay4lwegb3xr2wj;
alter table if exists book_copy drop constraint if exists FK97ooaf6exwl2n7hfx40gt3mjk;
alter table if exists bookshelf drop constraint if exists FKb7b2wqfkshgjlnfq80wuuv2rq;
alter table if exists catalog drop constraint if exists FKth4yhq6olxgommh0qflkf5fqx;
drop table if exists author cascade;
drop table if exists book cascade;
drop table if exists book_author cascade;
drop table if exists book_basket cascade;
drop table if exists book_copy cascade;
drop table if exists bookshelf cascade;
drop table if exists catalog cascade;
drop table if exists category cascade;
drop table if exists editor cascade;
drop table if exists library cascade;
drop table if exists member cascade;
alter table if exists book drop constraint if exists FKevj08i66fju1rmrbddcvu3nxy;
alter table if exists book drop constraint if exists FKam9riv8y6rjwkua1gapdfew4j;
alter table if exists book drop constraint if exists FKpmv0yeqvng13trnm9so4aaq04;
alter table if exists book_author drop constraint if exists FKbjqhp85wjv8vpr0beygh6jsgo;
alter table if exists book_author drop constraint if exists FKddiaong6i51tm6bl4ordev531;
alter table if exists book_copy drop constraint if exists FKoavt6bvftkhay4lwegb3xr2wj;
alter table if exists book_copy drop constraint if exists FK97ooaf6exwl2n7hfx40gt3mjk;
alter table if exists bookshelf drop constraint if exists FKb7b2wqfkshgjlnfq80wuuv2rq;
alter table if exists catalog drop constraint if exists FKth4yhq6olxgommh0qflkf5fqx;
drop table if exists author cascade;
drop table if exists book cascade;
drop table if exists book_author cascade;
drop table if exists book_basket cascade;
drop table if exists book_copy cascade;
drop table if exists bookshelf cascade;
drop table if exists catalog cascade;
drop table if exists category cascade;
drop table if exists editor cascade;
drop table if exists library cascade;
drop table if exists member cascade;
